### ISSUE TITLE
 哥们在吗，你的项目下载下来运行了包jsp解析错误，能指点下吗

### ISSUE THREAD

**Issue by zhazhahui666** [zhaoml529/SpringOA#11]
你的项目下载下来运行了包jsp解析错误，能指点下吗

**Comment by zhaoml529** [comment]
环境里是否有servlet的jar包

**Comment by zhazhahui666** [comment]
哥们，搞定了，谢了，是因为我用的是tomcat8导致的，换成7就ok了




------------------ 原始邮件 ------------------
发件人: "zml";<notifications@github.com>;
发送时间: 2017年12月19日(星期二) 中午11:48
收件人: "zhaoml529/SpringMVC-Activiti5.16-Shiro"<SpringMVC-Activiti5.16-Shiro@noreply.github.com>;
抄送: "陈亮"<1119331512@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhaoml529/SpringMVC-Activiti5.16-Shiro] 哥们在吗，你的项目下载下来运行了包jsp解析错误，能指点下吗 (#11)




环境里是否有servlet的jar包
