### ISSUE TITLE
环境搭建求助

### ISSUE THREAD

**Issue by fuwj1994** [zhaoml529/SpringOA#15]
感谢您的分享，这个程序和我目前要做的事情有很多相似的地方，想下载下来看一下运行效果学习学习。但是遇到了一些问题...
我使用的是IDEA IU集成开发环境，jdk版本为1.8.0，TomCat版本为7.0，运行之后出现了404错误，图片无法插入，我只能把问题转换成文字如下:
HTTP Status 404 - /
type Status report
message /
description The requested resource is not available.
Apache Tomcat/7.0.88

不知是哪里出了问题，可否有解决方法？我的邮箱是fuwj1993@163.com
希望收到您的回复，谢谢您！
祝 好！

**Comment by zhaoml529** [comment]
由于此项目时间比较长，我记得jdk需要1.7版本，1.8可能会有问题。用IDEA开发时别忘记引入lib目录下的jar包
