### ISSUE TITLE
新建的请假单经理和总监都看不到

### ISSUE THREAD

**Issue by ren-xianwei** [zhaoml529/SpringOA#17]
如题

**Comment by zhaoml529** [comment]
是否按照说明正确操作？说明中的第3条：
“审批设定界面点击初始化按钮，将每个流程描述文件中的用户任务节点初始化到t_user_task表中，此表是用作管理每个流程审批人员的。初始化完成后，逐个设定审批人员（点击设定人员按钮即可）”

**Comment by menglingsheng** [comment]
有数据库吗

**Comment by ren-xianwei** [comment]
你好：
      谢谢你的回复，原因找到了，节点没有设置人员，但也有个bug，选择组的功能不好使。
