### ISSUE TITLE
icon.css

### ISSUE THREAD

**Issue by FRunning** [zhaoml529/SpringOA#18]
你好，那个icon,css里面的图片引用错误，可以跟新一下imgages中这个文件夹吗

**Comment by zhaoml529** [comment]
图片，js等文件应该作为资源文件进行访问，并且不会被拦截，检查一下您使用的方式

**Comment by FRunning** [comment]
你好：
     我的意思是在images文件夹下面没有icon这个文件夹，所以导致icon.css文件加载错误



------------------ 原始邮件 ------------------
发件人: "zml"<notifications@github.com>;
发送时间: 2018年9月11日(星期二) 下午3:48
收件人: "zhaoml529/SpringMVC-Activiti5.16-Shiro"<SpringMVC-Activiti5.16-Shiro@noreply.github.com>;
抄送: "梦雨人"<904069962@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhaoml529/SpringMVC-Activiti5.16-Shiro] icon.css (#18)




图片，js等文件应该作为资源文件进行访问，并且不会被拦截，检查一下您使用的方式

**Comment by zhaoml529** [comment]
因为此项目时间久远，我也记不清有没有这个文件夹，所以如果没有影响到页面展示的话就忽略这个问题。
