### ISSUE TITLE
不理解怎么login的.

### ISSUE THREAD

**Issue by metalbreeze** [zhaoml529/SpringOA#20]
showLoginForm 只会返回login 页面，没有看到有验证密码的环节。
怎么成功后，就跳到另index呢

**Comment by Jupeng98** [comment]
登陆不上啊，密码不对

**Comment by zhaoml529** [comment]
@metalbreeze
基于Form表单的身份验证过滤器 CustomFormAuthenticationFilter，此方法继承了shiro的FormAuthenticationFilter，实际登录方法是调用FormAuthenticationFilter中的onAccessDenied方法，判断如果是登录请求，就调用executeLogin方法，此方法中的subject.login(token);就是登录了。
