### ISSUE TITLE
请问这项目现在如何了

### ISSUE THREAD

**Issue by magiczero** [zhaoml529/SpringOA#6]
如题，正在研究

**Comment by zhaoml529** [comment]
这个项目现在可以用的，基本功能都有了。

**Comment by magiczero** [comment]
请教个问题，如果我想把Activiti的表单，也就是JavaBean单独存在一个表中，已方便以后查询方便，请问如何能保证同时保存到Activiti和单表中的数据一致？用事务吗？

**Comment by magiczero** [comment]
我的意思是只能用事务来保证吗？

**Comment by zhaoml529** [comment]
是的，在你的业务中service层(事务)保存你的业务表单和调用Activiti的api操作Activiti表就可以。不知道我理解的和你表达的是否一致。

**Comment by magiczero** [comment]
谢谢，那还需要在Activiti的流程中保存一个任务参数为Serializable类型的JavaBean吗？或者说如何将这个流程与JavaBean关联起来？

**Comment by zhaoml529** [comment]
你可以在你的业务表中加入Activiti相关的字段，如：我们想追踪业务数据在流程中的实时状态，可以在业务表中加入processInstanceId、taskId、executionId达到和Activiti关联的目的。当然也可以像你说的那样，保存一个JavaBean或id(通过id查询JavaBean)到流程变量表中。

**Comment by magiczero** [comment]
嗯，这回明白了，谢谢！

**Comment by zhaoml529** [comment]
不谢，我关闭此Issues了。
