### ISSUE TITLE
调试不能跟踪代码

### ISSUE THREAD

**Issue by wzhenhang** [zhaoml529/SpringOA#7]
你好，我在eclipse下调试工程，能够单步跟踪，但无法查看变量，请问知道怎么回事吗？

**Comment by zhaoml529** [comment]
这个应该和代码没关系，你可以查查。点击eclipse的Window->Preferences->Java->Editor->Hovers, 勾选Variable Values,（如果Combined Hover已经选择了，就取消它）, 然后点击Apply。

**Comment by wzhenhang** [comment]
好的，多谢!

 

发件人: bounces+848413-5871-wzhenhang=163.com@sgmail.github.com [mailto:bounces+848413-5871-wzhenhang=163.com@sgmail.github.com] 代表 zml
发送时间: 2017年5月19日 10:34
收件人: zhaoml529/SpringMVC-Activiti5.16-Shiro
抄送: wzhenhang; Author
主题: Re: [zhaoml529/SpringMVC-Activiti5.16-Shiro] 调试不能跟踪代码 (#7)

 

这个应该和代码没关系，你可以查查。点击eclipse的Window->Preferences->Java->Editor->Hovers, 勾选Variable Values,（如果Combined Hover已经选择了，就取消它）, 然后点击Apply。
